spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall_tiny?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password:
  redis:
    host: localhost # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: # Redis服务器连接密码（默认为空）
    timeout: 3000ms # 连接超时时间（毫秒）
  mail:
    host: smtp.mxhichina.com
    password: Hypeeyes123
    username: contact@hypeeyes.com
    port: 25
    test-connection: false
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.socketFactory.fallback: true
      mail.smtp.starttls.enable: true

logging:
  level:
    root: info
    com.macro.mall: debug

# OSS相关配置信息
aliyun:
  oss:
    endpoint: oss-cn-hongkong.aliyuncs.com # oss对外服务的访问域名
    accessKeyId: LTAI4Fn3XfzEPgeHBfcu5CmA # 访问身份验证中用到用户标识
    accessKeySecret: baf8yIurNHHHOCh6TktQlvZbsUZiAe # 用户用于加密签名字符串和oss用来验证签名字符串的密钥
    bucketName: hypeeyes-linbo # oss的存储空间
    policy:
      expire: 300 # 签名有效期(S)
    maxSize: 10 # 上传文件大小(M)
    callback: http://localhost:8080/aliyun/oss/callback # 文件上传成功后的回调地址
    dir:
      prefix: attachment/ # 上传文件夹路径前缀
